app = "geometry-shooter-vincent"   # 建议加个年份后缀，避免重名
primary_region = "sin"          # 新加坡，延迟最低

[build]
  [build.env]
    NODE_VERSION = "18"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"